langage: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq virtualbox
 - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
 - sudo dpkg -i vagrant_1.7.2_x86_64.deb

script:
  - vagrant up

branches:
  only:
    - master
    - dev

notifications:
  email: false